# Minimal public Codecov config
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: auto
        threshold: 2%
        informational: true

ignore:
  - "datasets/**"
  - "**/*.ipynb"
  - "**/__pycache__/**"
