name: pyparticle-partmc
channels:
- conda-forge
- defaults
dependencies:
- netcdf4
- python=3.9
- pip
- numpy
- scipy
- matplotlib
- pyprojroot
- pyyaml
- arviz
- pip:
  - pytest
  - pytest-cov
  - codecov
  - pymiescatt
