[project]
name = "pyparticle"
version = "0.1.0"
description = "Describing and analyzing aerosol particles and particle populations"
readme = "README.md"
authors = [
    { name = "Laura Fierce" }
]
requires-python = ">=3.11"
dependencies = [ # (explicitly) stated in the code
    "netcdf4",
    "pandas",
    "numpy", "scipy", 
    "pymc",
    ]
[dependency-groups]
dev = [
    # interactive computing
    "ipython", 'marimo',
    # debugging
    "ipdb", "icecream",
    # plotting
    'holoviews',
    # utils
    "pyprojroot",  # getting root dir
    # for comparisons
    "PyMieScatt",
    ]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
