[project]
name = "pyparticle"
version = "0.1.0"
description = "Describing and analyzing aerosol particles and particle populations"
readme = "README.md"
authors = [
    { name = "Laura Fierce" }
]
requires-python = ">=3.9"
dependencies = [
    "netcdf4",
    "pandas",
    "numpy",
    "scipy",
    "pymc",
]

[project.optional-dependencies]
dev = [
    "ipython",
    "marimo",
    "ipdb",
    "icecream",
    "holoviews",
    "matplotlib",
    "pyprojroot",
    "PyMieScatt",
    "pytest",
    "pytest-regressions[num]",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
