# TO *RUN* partmc
FROM fedora

RUN dnf -y update \
    && dnf -y install \
        less \
        tmux \
        gcc-gfortran \
        make \
        netcdf-fortran-devel \
        gsl-devel \
        cmake \
    && dnf clean all

RUN dnf -y install git
# WARNING: should spec a specific commit
RUN git clone https://github.com/compdyn/partmc.git

RUN mkdir /build \
    && cd /build \
    && cmake -D CMAKE_BUILD_TYPE=release \
             -D CMAKE_C_FLAGS_RELEASE="-O2 -g -Werror -Wall -Wextra" \
             -D CMAKE_Fortran_FLAGS_RELEASE="-O2 -g -Werror -fimplicit-none -Wall -Wextra -Wconversion -Wunderflow -Wimplicit-interface -Wno-compare-reals -Wno-unused -Wno-unused-parameter -Wno-unused-dummy-argument -fbounds-check" \
             -D ENABLE_GSL:BOOL=TRUE \
             /partmc \
    && make

# binaries are here
ENV PATH=$PATH:/build
RUN mkdir /work
# access source code from /partmc
WORKDIR /work
# have to copy it to separate code from exec!
#cp -r /partmc/scenarios/1_urban_plume .
# partmc urban_plume.spec
