name: Run Python Tests and Upload Coverage

on:
  push:
    branches: [refactor, main, master]
  pull_request:
    branches: [refactor, main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: pyparticle  # <-- Replace with your env name if different
          auto-activate-base: false
          python-version: 3.10

      - name: Show environment info
        run: |
          conda info
          conda list

      - name: Install extra dependencies for testing and coverage
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov codecov

      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
