name: Test and Upload Coverage

on:
  push:
    branches: [main, master, refactor]
  pull_request:
    branches: [main, master, refactor]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: pyparticle
          auto-activate-base: false

      - name: Install pip-only packages (if not in environment)
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov codecov

      - name: Run tests and collect coverage
        shell: bash -l {0}
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
