name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package + dev deps
        run: |
          python -m pip install --upgrade pip
          # If you have extras defined:
          pip install -e .[dev]
          # Fallback if not: pip install -e . pytest pytest-cov ruff mypy

      - name: Lint (ruff)
        run: ruff check src tests || true

      - name: Type check (mypy)
        run: mypy || true

      - name: Run tests with coverage (xml)
        run: |
          pytest -q --cov=pyparticle --cov-report=xml:coverage.xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
          verbose: true
