name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package + test deps (robust)
        run: |
          python -m pip install --upgrade pip
          # Try dev extras; fall back to base + explicit pytest deps
          pip install -e .[dev] || (pip install -e . && pip install pytest pytest-cov)

      - name: Sanity: pytest & import pyparticle
        run: |
          python - <<'PY'
          import sys
          import pytest
          print("pytest:", pytest.__version__, "python:", sys.version.split()[0])
          try:
            import pyparticle
            print("pyparticle from:", getattr(pyparticle, "__file__", None))
          except Exception as e:
            print("IMPORT ERROR:", e); raise
          PY

      - name: Run tests with coverage (xml + terminal)
        run: |
          python -m pytest -q --cov=pyparticle --cov-report=xml:coverage.xml --cov-report=term-missing
