name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package + dev deps
        run: |
          python -m pip install --upgrade pip
          # If you defined a [project.optional-dependencies].dev extra, keep the first line.
          # Otherwise, the fallback line installs the package without extras.
          pip install -e .[dev] || pip install -e .

      - name: Sanity: import pyparticle
        run: |
          python - <<'PY'
          import sys
          print("sys.path[0:3]:", sys.path[0:3])
          import pyparticle
          print("pyparticle loaded from:", pyparticle.__file__)
          PY

      - name: Run tests with coverage (xml + terminal)
        run: |
          pytest -q --cov=pyparticle --cov-report=xml:coverage.xml --cov-report=term-missing

      # Optional: enforce minimum coverage (set MIN_COVERAGE to taste, or leave 0)
      - name: Enforce minimum coverage
        env:
          MIN_COVERAGE: "0"
        run: |
          python - <<'PY'
          import os, sys, xml.etree.ElementTree as ET
          rate = float(ET.parse('coverage.xml').getroot().get('line-rate') or 0.0) * 100
          thresh = float(os.environ.get('MIN_COVERAGE','0'))
          print(f"Coverage: {rate:.2f}% (min {thresh:.2f}%)")
          if (summary := os.environ.get('GITHUB_STEP_SUMMARY')):
              with open(summary,'a') as f: f.write(f"## Test coverage\n\n- **Line coverage:** {rate:.2f}%\n- **Threshold:** {thresh:.2f}%\n")
          if rate < thresh: sys.exit(1)
          PY

      - name: Build HTML coverage report
        run: |
          python -m pip install coverage
          coverage html -i -d htmlcov

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage.xml
            htmlcov/
          retention-days: 7
