name: Test and Upload Coverage

on:
  push:
    branches: [main, master, refactor]
  pull_request:
    branches: [main, master, refactor]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: pyparticle
          auto-activate-base: false

      - name: Upgrade pip and install build tools
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install setuptools wheel hatchling

      - name: Install package (editable mode) with dev dependencies
        shell: bash -l {0}
        run: |
          pip install -e .[dev]

      - name: Show installed packages for debugging
        shell: bash -l {0}
        run: |
          pip list

      - name: Run tests and collect coverage
        shell: bash -l {0}
        run: |
          pytest --cov=pyparticle --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
